# Generated by Django 3.1.3 on 2020-11-15 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='Image',
            field=models.ImageField(null=True, upload_to='static/media/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='Image_category',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='Image_location',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
