# Generated by Django 3.1.3 on 2020-11-16 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0002_auto_20201115_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='Image',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='Image_description',
            field=models.CharField(max_length=100),
        ),
    ]
