# Generated by Django 3.1.3 on 2020-11-19 21:50

import cloudinary.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0003_auto_20201116_0529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='Image_category',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='image',
            name='Image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='location',
            name='Image_location',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
