# Generated by Django 3.1.3 on 2020-11-19 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0004_auto_20201120_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='Image_category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='image',
            name='Image_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='location',
            name='Image_location',
            field=models.CharField(max_length=100),
        ),
    ]
